# Example configuration

git-working-dir = "/home/me/my-repo"
http-port = 4000
auth-user = "me"
auth-password = "pass"
github-secret-token = "secret"
github-repos = ["mpowered/example"]
static-directory = "static"

github-oauth-client-id = "..."
github-oauth-client-secret = "..."
github-oauth-callback-url = "https://example.com/auth/github/callback"
github-authorized-team = "core"
github-authorized-organization = "mpowered"
github-test-team = "testers"

[database]
host = "localhost"
port = 5432
name = "lodjur"
user = "lodjur"
password = "lodjur"

[[deployments]]
name = "my-deployment-1"
warn = false
test = true

[[deployments]]
name = "my-deployment-2"
warn = true
test = false
