resolver: lts-13.27   # 8.6.5
extra-deps:
- github
- beam-migrate-0.4.0.1
- beam-postgres-0.4.0.0
- jwt-0.9.0
- servant-github-webhook-0.4.1.0
- servant-pipes-0.15
- git: https://github.com/bflyblue/servant-event-stream.git
  commit: f7af41ab81073ae054631baa4f8c9ecf6c8bc944
nix:
  packages:
  - postgresql_11
  - zlib
